version: '3.8'

volumes:
  postgres_data:
  static_volume:
  nginx:

services:
  db:
    image: postgres:12.4
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
    container_name: web
    restart: always
    volumes:
      - static_value:/code/static/
      - nginx:/code/nginx/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    volumes:
      - static_volume:/static/
      - nginx:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - web
